edited lloger module by added write streams
Kost90/nodejs24_hw_Kostiantyn pull request #6
Opened 2024-05-03 11:53 UTC by Kost90

2024-05-03 16:59 UTC, evhenious commented on utils/logger.js
> +  fs.writeFile(logsInfoPath, "", (error) => {
Що зміниться якщо ти убереш оці дві штуки `fs.writeFile`? І взагалі, поясни сенс для чого ти це додав? (Це не просто риторичне питання, а реальне запрошення до диалогу :) )

2024-05-03 17:03 UTC, evhenious commented on utils/logger.js
> +writeInfoStream.on("finish", () => {
Хороші варіанти логати ці події, але подивись - в тебе по дві однакові анонімні функції (для івента onFinish х2 і для onError х2). Старайся не повторювати себе, винеси їх як окремі нормальні функції з іменами і просто причепи на кожний стрім

2024-05-03 17:09 UTC, evhenious commented on utils/logger.js
> +  const isoDate = currentDate.toISOString().split("T")[0];
Чому залишаєш тільки дату? Уяви, в тебе реальний сервер, який обслуговує купу клієнтських запитів. Сотні запитів за хвилину. І в логах ти зберігаєш тільки дату подіЇ - вгадай з трьох разів, сильно корисні логи будуть :) особливо якщо шукати якусь проблему локалізовану в часі? )) 

Зазвичай, записи в лог містять час до мілісекунди, це буває дуже важливо. Тому будь ласка, просто `toISOString()` без split, добре? )

2024-05-03 17:12 UTC, evhenious commented on utils/logger.js
> +  const isoDate = currentDate.toISOString().split("T")[0];
Стосується також методів warn і error

2024-05-03 17:15 UTC, evhenious requested changes
Дві проблеми, які треба обов'язково поправити
- виводь в лог стріми дату разом з часом (див. коменти з деталями)
- у тебе щоразу при запуску лог файли перезаписуються, тобто містять тільки інфу з останнього запуску. Це не дуже ок, уяви в тебе сервер ребутнувся і всі попередні логи скажімо, за день затер. Знайди спосіб і поправ це - щоб нові запуски ДОДАВАЛИ строки до існуючих (підказка - подивись в опції створення файлстрімів)

2024-05-06 11:47 UTC, Kost90 commented on utils/logger.js
> +  fs.writeFile(logsInfoPath, "", (error) => {
Це, я щось намутив)) в мене була помилка, але вона була в іншому, що ці файлі створювались в папці utils) короче, одне виправив інше забув прибрати)) дякую:))

2024-05-06 11:53 UTC, Kost90 commented on utils/logger.js
> +writeInfoStream.on("finish", () => {
дякую

2024-05-06 16:29 UTC, evhenious approved these changes

2024-05-06 16:29 UTC, merged