created hw-6
Kost90/nodejs24_hw_Kostiantyn pull request #8
Opened 2024-05-20 12:36 UTC by Kost90

Привіт,

щось не дуже мені подобається код, який я зробив в частині мідлеварів, але все працює) 

Буду вдячний за коменти)

2024-05-20 17:32 UTC, evhenious commented on utils/morganLogger.js
> +const rootFolder = path.resolve(__dirname, "../");
Прикольно що ти використав наші старі логстріми :)

2024-05-20 17:48 UTC, evhenious requested changes
Головна задача - розділити валідатори від основної логіки

2024-05-20 17:48 UTC, evhenious commented on utils/morganLogger.js
> +  function accessLogger(tokens, req, res){
А ось тут трохи перестарався. Або передаєш формат стрінгу типу `:date :status ....`, або передаєш кастомну функцію, що приймає параметр `token`. Щось одне із цього )

В простих випадках типу нашого, абсолютно достатньо формат стрінги. Я б зробив краще отак і все
```javascript
function accessLogger(...args){
  consoleLogger(...args);
  streamLogger(...args);
}
```

2024-05-20 17:48 UTC, evhenious commented on server_express.js
> +const json = express.json();
Давай або так
```javascript
app.use(express.json());
```

або вже так
```javascript
const jsonParser = express.json();
app.use(jsonParser);
```

:) щоб не виникало питань "а що це за json тут такий передається"

2024-05-20 17:48 UTC, evhenious commented on routes/users.js
> +    res.statusCode = 200;
Можна 200 явно не прописувати - воно буде дефолтним і так

2024-05-20 17:48 UTC, evhenious commented on midleware/validators.js
> +const validateUserId = async (req, res, next) => {
Ти чомусь зліпив все в одну кучу. Те що має тут бути - валідатор окремо, основний хендлер окремо. 

І валідатор не впливає на успішні відповіді, він тільки фейлить з помилкою 400 якщо валідація не пройшла, і передає керування далі через next() якщо валідація пройшла

2024-05-20 17:48 UTC, evhenious commented on midleware/validators.js
> +const validateUserId = async (req, res, next) => {
В роутері на це повинно виглядати так
```javascript
router.post('/user', validateUserData, (req, resp) => { 
  // main handler where you make successful response
});

router.get('/user/:userId', validateUserId, (req, resp) => { 
  // main handler where you make successful response
});

router.delete('/user/:userId', validateUserId, (req, resp) => { 
  // main handler where you make successful response
});
```

І зверни увагу, валідатору має бути пофіг на якому методі він висить (GET, DELETE, ...), він має тільки знати про параметри або дані, які валідує

2024-05-21 14:46 UTC, Kost90 commented on midleware/validators.js
> +const validateUserId = async (req, res, next) => {
Дякую за коменти, якщо правильно зрозумів, то все виправив))

2024-05-21 19:32 UTC, evhenious commented on midleware/userIdChecker.js
> +const UserIdChecker = async (req, res, next) => {
Доречі, якщо це не клас, то краще не починати назву з великої літери

2024-05-21 19:37 UTC, evhenious commented on midleware/userIdChecker.js
> +      res.body = userId;
якщо хочеться прокидати щось своє через оці стандартні речі типу req, resp, то 
1. краще робити це НЕ через стандартні назви (в ідеалі додавай ключі які починаються із _ типу `req._myParam`)
2. Краще прокидати через `req` - бо це дані пов'язані із ріквестом :)

2024-05-21 19:38 UTC, evhenious approved these changes
Стало краще!

2024-05-21 19:38 UTC, merged